# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Oct 31 16:03:55 CET 2012
#
#/ usage: digirest:doc [ --url|-u <https://api.digipost.no>] 

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print SYNTAX and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo >&2 -e "\033[31m""SYNTAX: $*""\033[0m"
    else echo >&2 "SYNTAX: $*" 
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_usage
}

# options: [url]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --url|-u) rerun_option_check $# ; URL=$2 ; shift ;;
        # help option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$URL" ] && URL="https://api.digipost.no"
# Check required options are set

# If option variables are declared exportable, export them.

#
return 0
